"""initial_full_schema

Revision ID: 93dd6c1d002e
Revises: 
Create Date: 2025-06-11 12:35:57.897261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93dd6c1d002e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('aluno', 'possui_necessidade_especial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('incidente', 'descricao',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('incidente', 'tipo_incidente',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('incidente', 'status_resolucao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('motorista', 'status_ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('pontodeparada', 'endereco',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('pontodeparada', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('pontodeparada', 'longitude',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('rota', 'descricao',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('rota', 'limite_atrasos_semanal',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rota', 'ativa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('veiculo', 'status_manutencao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('veiculo', 'adaptado_pcd',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('veiculo', 'ano_fabricacao',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('viagem', 'vagas_ocupadas',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viagem', 'vagas_ocupadas',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('veiculo', 'ano_fabricacao',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('veiculo', 'adaptado_pcd',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('veiculo', 'status_manutencao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rota', 'ativa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('rota', 'limite_atrasos_semanal',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rota', 'descricao',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('pontodeparada', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    op.alter_column('pontodeparada', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    op.alter_column('pontodeparada', 'endereco',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('motorista', 'status_ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('incidente', 'status_resolucao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('incidente', 'tipo_incidente',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('incidente', 'descricao',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('aluno', 'possui_necessidade_especial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
